services:
  mysql-server:
    container_name: react-navigation-module-mysql-server
    restart: always
    image: ${MYSQL_SERVER_IMAGE}:${MYSQL_SERVER_TAG}
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_EXPOSE_PORT:-3330}:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql:rw

  zabbix-server-mysql:
    container_name: react-navigation-module-zabbix-server-mysql
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        ZABBIX_SERVER_IMAGE: ${ZABBIX_SERVER_IMAGE}
        ZABBIX_SERVER_TAG: ${ZABBIX_SERVER_TAG}
    ports:
      - 10051:10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - /usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - /var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - /var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - /var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - /var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - /var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - /var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
    depends_on:
      - mysql-server

  zabbix-web-nginx-mysql:
    container_name: react-navigation-module-zabbix-web-nginx
    restart: always
    image: ${ZABBIX_WEB_IMAGE}:${ZABBIX_WEB_TAG}
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /etc/ssl/nginx:/etc/ssl/nginx
      - /usr/share/zabbix/modules/:/usr/share/zabbix/modules/
      - ./../zabbix-module:/usr/share/zabbix/modules/ReactModule
    environment:
      - ZBX_SERVER_NAME=${ZBX_SERVER_NAME}
      - ZBX_SERVER_HOST=zabbix-server-mysql
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql-server
      - zabbix-server-mysql

  zabbix-java-gateway:
    container_name: react-navigation-module-zabbix-java-gateway
    restart: always
    image: zabbix/zabbix-java-gateway:ubuntu-7.0-latest
    ports:
      - 10052:10052

  grafana-server:
    container_name: react-navigation-module-grafana-server
    restart: always
    image: ${GRAFANA_SERVER_IMAGE}:${GRAFANA_SERVER_TAG}
    ports:
      - 3000:3000
    volumes:
      - /var/lib/grafana:/var/lib/grafana
    user: "root:root"
    environment:
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=mysql-server
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=grafana
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
